// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	errors "github.com/tkeel-io/kit/errors"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ego package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

var resourceErrUnknown *errors.TError
var resourceErrNotFound *errors.TError
var resourceErrListMysql *errors.TError
var resourceErrInfoMysql *errors.TError

func init() {
	resourceErrUnknown = errors.New(int(codes.Unknown), "helloworld.v1.RESOURCE_ERR_UNKNOWN", Error_RESOURCE_ERR_UNKNOWN.String())
	errors.Register(resourceErrUnknown)
	resourceErrNotFound = errors.New(int(codes.NotFound), "helloworld.v1.RESOURCE_ERR_NOT_FOUND", Error_RESOURCE_ERR_NOT_FOUND.String())
	errors.Register(resourceErrNotFound)
	resourceErrListMysql = errors.New(int(codes.Internal), "helloworld.v1.RESOURCE_ERR_LIST_MYSQL", Error_RESOURCE_ERR_LIST_MYSQL.String())
	errors.Register(resourceErrListMysql)
	resourceErrInfoMysql = errors.New(int(codes.Internal), "helloworld.v1.RESOURCE_ERR_INFO_MYSQL", Error_RESOURCE_ERR_INFO_MYSQL.String())
	errors.Register(resourceErrInfoMysql)
}

func ResourceErrUnknown() errors.Error {
	return resourceErrUnknown
}

func ResourceErrNotFound() errors.Error {
	return resourceErrNotFound
}

func ResourceErrListMysql() errors.Error {
	return resourceErrListMysql
}

func ResourceErrInfoMysql() errors.Error {
	return resourceErrInfoMysql
}
