annotations:
  tkeel.io/deployment-name: rule-manager
  tkeel.io/enable: "true"
  tkeel.io/plugin-port: "31234"
  tkeel.io/tag: manager
  tkeel.io/version: v0.4.0
apiVersion: v2
appVersion: 1.0.0
description: 后端租户平台的「数据路由」插件
name: rule-manager
type: application
version: 1.0.0
maintainers:
  - email: tkeel@yunify.com
    name: tkeel
